app:
  appName: assignment
  port: 8000

logger:
  consoleLoggingEnabled: true
  fileName: ../../logs/access.log
  errorFileName: ../../logs/error.log
  maxSizeInMB: 1024
  maxBackups: 10
  maxAgeInDays: 2
  compress: true

smRedis:
  host: redis-14119.c321.us-east-1-2.ec2.cloud.redislabs.com
  port: 14119
  password: BeBdc3e6gWVXKal5avrEAQPsBZajboiK
  user: default

mongoDb:
  host: cluster0.wraelmn.mongodb.net
  port: 5432
  password: CfVhlA8niJNyozwx
  user: dazzling420_db_user
  db_name: dev_portal
