app:
  appName: assignment
  port: 8000

logger:
  consoleLoggingEnabled: true
  fileName: ../../logs/access.log
  errorFileName: ../../logs/error.log
  maxSizeInMB: 1024
  maxBackups: 10
  maxAgeInDays: 2
  compress: true

smRedis:
  host: redisHost 
  port: 14119
  password: redisPassword
  user: default

mongoDb:
  host: mongoDb_Host
  port: 5432
  password: mongoDbPassword
  user: mongoDbUser
  db_name: mongoDbName
